### ISSUE TITLE
ERROR: You need to have Ruby and Compass installed and in your system PATH for this task to work

### ISSUE THREAD

**Issue by Xalsar** [smerth/gulp-4-site-builder-jade-coffeescript-bootstrap#1]
I installed ruby on Ubuntu via [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-16-04), because I need it for this repo.

When I ran gulp, this message appears:
```
{ [Error: You need to have Ruby and Compass installed and in your system PATH for this task to work.]
  message: 'You need to have Ruby and Compass installed and in your system PATH for this task to work.',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-compass',
  __safety: { toString: [Function: bound ] } }
```
But I already have ruby and compass installed and in my system path:
```
xavier@xavier-G10AC:~$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
xavier@xavier-G10AC:~$ compass -v
Compass 1.0.3 (Polaris)
Copyright (c) 2008-2018 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
xavier@xavier-G10AC:~$ echo $PATH
/home/xavier/.rbenv/shims/compass:/home/xavier/.rbenv/shims/ruby:/home/xavier/.rbenv/shims:/home/xavier/.rbenv/bin:/home/xavier/.rbenv/shims/compass:/home/xavier/.rbenv/shims/ruby:/home/xavier/.rbenv/shims:/home/xavier/.rbenv/bin:/home/xavier/.rbenv/shims/compass:/home/xavier/.rbenv/shims/ruby:/home/xavier/.rbenv/shims:/home/xavier/.rbenv/bin:/home/xavier/.rbenv/shims:/home/xavier/.rbenv/bin:/home/xavier/.rbenv/shims:/home/xavier/.rbenv/bin:/home/xavier/.local/share/umake/bin:/home/xavier/bin:/home/xavier/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
Is it my fault? Or is it a bug?

Thanks.

**Comment by smerth** [comment]
Hi Xalsar, 

I haven't worked with this repo for a long time and just downloaded it and installed the npm modules and then ran `gulp bower` and `gulp vendor` and then `gulp` to serve the site.  Everything seems to be working fine.

Compass is processing the stylesheets so my guess is it is related to your system setup (that's what the error seems to suggest, rather than an error with the configuration of a gulp task).  

I'm not familiar with Ubuntu specifically so I am not sure I can help.  But let me know if you find an answer...

**Comment by smerth** [comment]
I have refactored the repo since this issue.  It no longer be a problem
